package de.henzeob.inventory.model.enums;

public enum CommandType {
    ITEM_CREATE, ITEM_UPDATE, ITEM_DELETE,
    CONTAINER_CREATE, CONTAINER_UPDATE, CONTAINER_DELETE,
    CATEGORY_CREATE, CATEGORY_UPDATE, CATEGORY_DELETE,
    ITEM_IMAGE_CREATE, ITEM_IMAGE_DELETE,
    CONTAINER_IMAGE_CREATE, CONTAINER_IMAGE_DELETE
}
